In [15]:
import numpy as np
import pandas as pd

In [10]:
np.random.seed(1)
sales=np.random.randint(70,size=(5,4))

In [11]:
sales

array([[37, 12,  9,  5],
       [64, 16,  1,  6],
       [25, 50, 20, 18],
       [11, 28, 29, 14],
       [50, 68, 13,  9]])

In [18]:
Weekly_Game_Sales = pd.DataFrame(sales,index=["Mon","Tue","Wed","Thurs","Fri"],
                                columns=["Horiz","GOW","Ark","Spi"])

In [19]:
Weekly_Game_Sales


Horiz  GOW  Ark  Spi
Mon       37   12    9    5
Tue       64   16    1    6
Wed       25   50   20   18
Thurs     11   28   29   14
Fri       50   68   13    9

In [37]:
np.random.seed(5)
pricesf=np.random.randint(70,size=(4,1))

In [38]:
pricesf

array([[61],
       [16],
       [ 8],
       [62]])

In [33]:
Prices = pd.DataFrame(prices,index=["Horiz","GOW","Ark","Spi"],columns=["Sales"])
                                

In [35]:
Weekly_Game_Sales

Horiz  GOW  Ark  Spi
Mon       37   12    9    5
Tue       64   16    1    6
Wed       25   50   20   18
Thurs     11   28   29   14
Fri       50   68   13    9

In [36]:
Prices

Sales
Horiz     61
GOW       16
Ark        8
Spi       62

In [43]:
Total_Sales=np.dot(pricesf.T,sales.T)

In [44]:
Total_Sales

array([[2831, 4540, 3601, 2219, 4800]])

In [52]:
Weekly_Game_Sales = Total_Sales

In [53]:
Weekly_Game_Sales

array([[2831, 4540, 3601, 2219, 4800]])

In [54]:
Weekly_Game_Sales = pd.DataFrame(sales,index=["Mon","Tue","Wed","Thurs","Fri"],
                                columns=["Horiz","GOW","Ark","Spi"])

In [55]:
Weekly_Game_Sales

Horiz  GOW  Ark  Spi
Mon       37   12    9    5
Tue       64   16    1    6
Wed       25   50   20   18
Thurs     11   28   29   14
Fri       50   68   13    9

In [60]:
Weekly_Game_Sales["Total_Profit Per Day"] = Total_Sales.T

In [61]:
Weekly_Game_Sales

Horiz  GOW  Ark  Spi  Total_Profit  Total_Profit Per Day
Mon       37   12    9    5          2831                  2831
Tue       64   16    1    6          4540                  4540
Wed       25   50   20   18          3601                  3601
Thurs     11   28   29   14          2219                  2219
Fri       50   68   13    9          4800                  4800

In [70]:
Weekly_Game_Sales.drop("Total_Profit",axis="columns",inplace=True)

In [71]:
Weekly_Game_Sales.drop("Total_Profit Per Day",axis="columns",inplace=True)

In [72]:
Weekly_Game_Sales["Total Profit Per Day"] = Total_Sales.T

In [73]:
Weekly_Game_Sales

Horiz  GOW  Ark  Spi  Total Profit Per Day
Mon       37   12    9    5                  2831
Tue       64   16    1    6                  4540
Wed       25   50   20   18                  3601
Thurs     11   28   29   14                  2219
Fri       50   68   13    9                  4800